"""empty message

Revision ID: 19e0d2bdfeae
Revises: 6ab01a8c6ad1
Create Date: 2022-07-16 12:58:14.781345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e0d2bdfeae'
down_revision = '6ab01a8c6ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reptiles', sa.Column('scientific_name', sa.String(length=250), nullable=True))
    op.add_column('reptiles', sa.Column('conservations_status', sa.String(length=250), nullable=True))
    op.add_column('reptiles', sa.Column('native_habitat', sa.String(length=250), nullable=True))
    op.drop_column('reptiles', 'sci_name')
    op.drop_column('reptiles', 'habitat')
    op.drop_column('reptiles', 'consv_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reptiles', sa.Column('consv_status', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('reptiles', sa.Column('habitat', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('reptiles', sa.Column('sci_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('reptiles', 'native_habitat')
    op.drop_column('reptiles', 'conservations_status')
    op.drop_column('reptiles', 'scientific_name')
    # ### end Alembic commands ###
