"""empty message

Revision ID: 2a8a874e7a38
Revises: 19e0d2bdfeae
Create Date: 2022-07-16 13:02:12.805683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8a874e7a38'
down_revision = '19e0d2bdfeae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reptiles', sa.Column('conservation_status', sa.String(length=250), nullable=True))
    op.drop_column('reptiles', 'conservations_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reptiles', sa.Column('conservations_status', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('reptiles', 'conservation_status')
    # ### end Alembic commands ###
