"""empty message

Revision ID: 6ab01a8c6ad1
Revises: 2bfe902242a5
Create Date: 2022-07-16 11:51:55.403302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab01a8c6ad1'
down_revision = '2bfe902242a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reptiles', sa.Column('consv_status', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reptiles', 'consv_status')
    # ### end Alembic commands ###
